apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-admin-portal-layout
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/name: fint-admin-portal-layout
    app.kubernetes.io/instance: fint-admin-portal-layout_fintlabs-no
spec:
  port: 3000
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-admin-portal-layout:sha-000000
  prometheus:
    enabled: true
    port: "3000"
    path: /metrics
  url:
    hostname: adminportalen.fintlabs.no
    basePath: /beta
  ingress:
    enabled: true
    middlewares:
      - fint-admin-portal-sso
  env: []