apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - application.yaml
  - layout-config-application.yaml
  - flais-sso.yaml
commonLabels:
  app.kubernetes.io/version: "latest"
  app.kubernetes.io/managed-by: core-team
  app.kubernetes.io/part-of: fint-admin-portal
  fintlabs.no/team: core
  fintlabs.no/org-id: fintlabs.no
