apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - patch: |-
      - op: replace
        path: "/spec/basePath"
        value: /beta/fintlabs-no
    target:
      kind: FLAISSso
      name: fint-admin-portal-sso
  - patch: |-
      - op: replace
        path: "/spec/url/basePath"
        value: /beta/fintlabs-no
    target:
      kind: Application
      name: fint-admin-portal-layout
  - patch: |-
      - op: replace
        path: "/spec/url/basePath"
        value: /beta/fintlabs-no/api/layout
    target:
      kind: Application
      name: fint-admin-portal-layout-config-service
  - patch: |-
      - op: add
        path: "/spec/env/-"
        value:
          name: LAYOUT_CONFIGURATION_URI
          value: http://fint-admin-portal-layout-config-service:8080/beta/fintlabs-no/api/layout/configuration
    target:
      kind: Application
      name: fint-admin-portal-layout

