apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-admin-portal-layout-config-service
  labels:
    app.kubernetes.io/component: config
    app.kubernetes.io/name: fint-admin-portal-layout-config-service
    app.kubernetes.io/instance: fint-admin-portal-layout-config-service_fintlabs-no
spec:
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/flais-layout-config-service:latest
  imagePullPolicy: Always
  url:
    hostname: admin-test.fintlabs.no
    basePath: /alpha/fintlabs-no/api/layout
  ingress:
    enabled: true
  database:
    enabled: true